name: Full App Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  Check-PR-Status:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev libssl-dev pkg-config

      - name: Setup Rust
        working-directory: ./src-tauri
        run: |
          rustup toolchain install stable
          rustup component add rustfmt clippy

      - name: Check JavaScript/TypeScript formatting
        run: npx prettier --check .

      - name: Setup Rust environment
        run: echo "RUSTFLAGS=-D warnings" >> $GITHUB_ENV

      - name: Check Rust formatting
        working-directory: ./src-tauri
        run: cargo fmt -- --check

      - name: Build Rust
        working-directory: ./src-tauri
        run: cargo build --verbose

      - name: Run Rust tests
        env:
          TG_ID: 1
          TG_HASH: a
        working-directory: ./src-tauri
        run: cargo test --verbose --all-features

      - name: Run JavaScript/TypeScript tests
        run: npm run test
